### ISSUE TITLE
Parallel version produces corrupted output

### ISSUE THREAD

**Issue by petersbr** [dontkme/EAHelitron#1]
Hi,

When running the parallel version, the final files end up being corrupted, probably because of the different forks simultaneously writing.  The single-threaded version works fine.

**Comment by dontkme** [comment]
Thanks for your report.
Could you give me the information of your system environment and input
genomes?
best regards


petersbr <notifications@github.com> 于2019年6月26日周三 上午7:15写道：

**Comment by petersbr** [comment]
I am not waiting on a solution to this, just thought you should know that the parallel version has some simultaneous-write issues so it can be fixed in some future release. 
 
System: CentOS 7.6.1810
perl: perl 5.26.2 x86_64-linux-thread-multi
Genomes: maize genomes

E.g. in the second line below
Chr01   EAhelitron      CDS     353336  353358  .       +       .       Name=Chr01H4.3;ID=Chr01H4;Parent=Chr01H4;Type=Helitron;Super_Family=Helitron
Chr01   EAhelitron      CDS     525192  525218  .       +       .       Name=Chr01H5.3;ID=Chr01H5;Parent=Chr01H5;TypChr01   EAhelitron      CDS     646561  646595  .       +       .       Name=Chr01H8.3;ID=Chr01H8;Parent=Cmily=Helitron
Chr01   EAhelitron      CDS     551495  551518  .       +       .       Name=Chr01H6.3;ID=Chr01H6;Parent=Chr01H6;Type=Helitron;Super_Family=Helitron
Chr01   EAhelitron      CDS     582526  582554  .       +       .       Name=Chr01H7.3;ID=Chr01H7;Parent=Chr01H7;Type=Helitron;Super_Family=Helitron

**Comment by dontkme** [comment]
Thanks again.  @petersbr 
I had consider the writing issues during coding, and designed the cache  part. I will confirm the error whether it comes in cache files or in final combine process.
