### ISSUE TITLE
Fasta header parsing doesn't handle `|`

### ISSUE THREAD

**Issue by darcyabjones** [dontkme/EAHelitron#2]
Hi there,

We've run into an issue running EAHelitron on genomes downloaded from the NCBI, which often contain `|` characters.

The regular expression that you use to extract the sequence id from Fasta headers doesn't handle this.
https://github.com/dontkme/EAHelitron/blob/c4c3dcae9aaa7c790dac49dc14927811ecf17b5b/EAHelitron#L107

I think taking the header up to the first space character is more commonly used in fasta parsing, would you consider updating it?
E.g. with the extended regular expression syntax `/^\s*>\s*(\S+)`.

Thanks in advance,
Darcy

**Comment by dontkme** [comment]
Hi Darcy,

Thanks for youc advice.

The main point of this regular expression is to get the key name of chromosome, the detail information after | or the first space is not necessary. The '.*' could represent all characters, contain |  or space, and the ' ?' could test a space exits or not. And in my opnion, '\s' of perl contains '\t', '\n'  and '\r', it may bring some mistakes druing reading fasta files, so I avoid using '\s' in this regular expression. 

So could you provide an example Fasta header which may failed reading the main name of sequence? Thanks in advence.

May be I could use `/^.*> *([a-zA-Z0-9_.-]+)[ |]?.*/`.
Feel free to fix it in your practice.

Best,
Kaining

**Comment by darcyabjones** [comment]
Hi Kaining,

Thanks for the reply.
This is the header format that I was given, i'm reporting this on behalf of a co-worker so I'm actually not sure where it's come from.
I assumed it was from the NCBI assembly database, but that doesn't seem to be the case.

`gnl|WGS:RZGK|Alen_Al4_ctg01|gb|RZGK01000002.1`

Which results in every sequence being labelled `gnl`.


RE spaces.
I get your point about extracting key names. I know it's commonly done in some communities but having the output GFF seqid field not match the input ID feels like it'll cause problems for many people using downstream programs (E.g. IGV).

The [GFF3 standard](
https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) officially supports characters in `a-zA-Z0-9.:^*$@!+_?-|` in the first field.

Splitting at the first non-leading space is probably the safest option and is what is done in most libraries.

Here's the regular expression used to extract the ID and description fields in [BioPerl](https://fastapi.metacpan.org/source/CJFIELDS/BioPerl-1.7.7/lib/Bio/SeqIO/fasta.pm).

```
if( $top =~ /^\s*(\S+)\s*(.*)/ ) {
    ($id,$fulldesc) = ($1,$2);
}
```

Seqan also splits at the first non-leading [space (including tabs)](https://github.com/seqan/seqan3/blob/9c7076ce7b3fc26e711c8e8d841b56429916b1bc/include/seqan3/core/char_operations/predicate.hpp#L163
) or [control character (including \r)](https://github.com/seqan/seqan3/blob/9c7076ce7b3fc26e711c8e8d841b56429916b1bc/include/seqan3/core/char_operations/predicate.hpp#L110-L111).

https://github.com/seqan/seqan3/blob/ac39faae31f8434f0d53b1ac73649c94ba3ccd7f/include/seqan3/io/sequence_file/format_fasta.hpp#L213-L216


It's fine If you're not keen on changing.
I'd probably just write pre and post-processing scripts to simplify the sequence id rather than maintain a fork of your software though.

**Comment by dontkme** [comment]
H

> Hi Kaining,
> 
> Thanks for the reply.
> This is the header format that I was given, i'm reporting this on behalf of a co-worker so I'm actually not sure where it's come from.
> I assumed it was from the NCBI assembly database, but that doesn't seem to be the case.
> 
> `gnl|WGS:RZGK|Alen_Al4_ctg01|gb|RZGK01000002.1`
> 
> Which results in every sequence being labelled `gnl`.
> 
> RE spaces.
> I get your point about extracting key names. I know it's commonly done in some communities but having the output GFF seqid field not match the input ID feels like it'll cause problems for many people using downstream programs (E.g. IGV).
> 
> The [GFF3 standard](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) officially supports characters in `a-zA-Z0-9.:^*$@!+_?-|` in the first field.
> 
> Splitting at the first non-leading space is probably the safest option and is what is done in most libraries.
> 
> Here's the regular expression used to extract the ID and description fields in [BioPerl](https://fastapi.metacpan.org/source/CJFIELDS/BioPerl-1.7.7/lib/Bio/SeqIO/fasta.pm).
> 
> ```
> if( $top =~ /^\s*(\S+)\s*(.*)/ ) {
>     ($id,$fulldesc) = ($1,$2);
> }
> ```
> 
> Seqan also splits at the first non-leading [space (including tabs)](https://github.com/seqan/seqan3/blob/9c7076ce7b3fc26e711c8e8d841b56429916b1bc/include/seqan3/core/char_operations/predicate.hpp#L163) or [control character (including \r)](https://github.com/seqan/seqan3/blob/9c7076ce7b3fc26e711c8e8d841b56429916b1bc/include/seqan3/core/char_operations/predicate.hpp#L110-L111).
> 
> https://github.com/seqan/seqan3/blob/ac39faae31f8434f0d53b1ac73649c94ba3ccd7f/include/seqan3/io/sequence_file/format_fasta.hpp#L213-L216
> 
> It's fine If you're not keen on changing.
> I'd probably just write pre and post-processing scripts to simplify the sequence id rather than maintain a fork of your software though.

Hi Darcy,

Thanks for your report and suggestions.
I have updated the code based on BioPerl. You could test the new script in your cases.
If you have other suggestions, please let me know.

Best,
Kaining

**Comment by darcyabjones** [comment]
Thanks Kaining,

And thanks for writing EAhelitron!
Have a great day :) 

Darcy
