### ISSUE TITLE
The gff file seems to be not right.

### ISSUE THREAD

**Issue by AntetokounmJie** [dontkme/EAHelitron#4]
Hi sir
  Sorry to bother you again. I try to run the EAHelitron as you advised.Then i check the gff file, i found it is a little weired.
  Here is ten line of it:
  1       EAhelitron      CDS     1250149 1250174 .       +       .       Name=1H1.3;ID=1H1;Parent=1H1;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     1549997 1550025 .       +       .       Name=1H2.3;ID=1H2;Parent=1H2;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     1535224 1535234 .       +       .       Name=1H2.5.1;ID=1H2.5.1;Parent=1H2;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     1541941 1541951 .       +       .       Name=1H2.5.2;ID=1H2.5.2;Parent=1H2;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     2208107 2208136 .       +       .       Name=1H3.3;ID=1H3;Parent=1H3;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     3711771 3711792 .       +       .       Name=1H4.3;ID=1H4;Parent=1H4;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     4226961 4226981 .       +       .       Name=1H5.3;ID=1H5;Parent=1H5;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     4221931 4221941 .       +       .       Name=1H5.5.1;ID=1H5.5.1;Parent=1H5;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     4222681 4222691 .       +       .       Name=1H5.5.2;ID=1H5.5.2;Parent=1H5;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     4710806 4710827 .       +       .       Name=1H6.3;ID=1H6;Parent=1H6;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     4721046 4721067 .       +       .       Name=1H7.3;ID=1H7;Parent=1H7;Type=Helitron;Super_Family=Helitron
1       EAhelitron      CDS     4711667 4711675 .       +       .       Name=1H7.5.1;ID=1H7.5.1;Parent=1H7;Type=Helitron;Super_Family=Helitron

As we can see, the interval between start and end is too small. And i dont think this is the right pos of the Helitron. Are you agree with me?
And i check the *.5.fa file, i found the each seq`s name seems  that contain the pos of each sequence, am i right?

Best regards

**Comment by dontkme** [comment]
Hi friend,

This position of each line means the terminal pos. A helitron's position is begin with .5 start pos to the end of .3 terminal. You could check the gff by loading it on IGV(Integrative Genomics Viewer).

And the name line do contain the pos of each sequence.

Thanks
